# Generated by Django 5.2.4 on 2025-08-08 00:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title for this menu", max_length=100),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique slug for this menu", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu",
                "verbose_name_plural": "Navigation Menus",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_title",
                    models.CharField(
                        blank=True,
                        help_text="Title to display for this menu item",
                        max_length=50,
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, help_text="URL for this menu item", max_length=500
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, help_text="Open this link in a new tab"
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page for this menu item",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="navigation.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
