# Generated by Django 5.2.4 on 2025-09-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.RenameField(
            model_name="menuitem",
            old_name="page",
            new_name="menu",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent menu item for nested menus",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="navigation.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.SlugField(
                help_text="Unique slug for this menu", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
