# Generated by Django 5.2.4 on 2025-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0003_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The title of the Cta.", max_length=256),
                ),
                (
                    "description",
                    models.TextField(help_text="A brief description for the Cta."),
                ),
                (
                    "button_text",
                    models.CharField(help_text="Text for the button.", max_length=256),
                ),
                ("button_url", models.URLField(help_text="URL for the button.")),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("cta", "CTA"),
                            ("button", "Button"),
                            ("link", "Link"),
                        ],
                        default="primary",
                        help_text="Style variant for the Cta",
                        max_length=50,
                    ),
                ),
                (
                    "header_script",
                    models.TextField(
                        blank=True,
                        help_text="Additional script to inject in the header when this CTA is used.",
                        null=True,
                    ),
                ),
                (
                    "footer_script",
                    models.TextField(
                        blank=True,
                        help_text="Additional script to inject in the footer when this CTA is used.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reusable CTA",
                "verbose_name_plural": "Reusable CTAs",
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("pricing", "Pricing"),
                    ("technical", "Technical"),
                ],
                default="general",
                help_text="Category for the FAQ",
                max_length=20,
            ),
        ),
    ]
