# docker-compose.yml
# For development environment

services:
  db:
    image: postgres:17-trixie # if you need to use normal postgres image
    container_name: wagtail-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    volumes:
      - wagtail_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_dev:/data

  s3:
    image: bitnami/minio:2025.4.22 ### !minio removed console ui in newer version; keep this version for DEV ###
    container_name: minio
    restart: unless-stopped
    volumes:
      - minio_data:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: bucket
      MINIO_SCHEME: http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: django-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - s3
    env_file:
      - ../.env
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ..:/app
      - django_venv:/app/.venv
      - frontend_node_modules:/app/frontend/node_modules
    ports:
      - "8000:8000" # Django
      - "5173:5173" # Vite
    networks:
      - default

volumes:
  wagtail_db_data:
  redis_dev:
  minio_data:
  django_venv:
  frontend_node_modules:
