# Generated by Django 5.2.4 on 2025-08-07 21:02

import apps.snippets.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_standardpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("paragraph", 3),
                    ("image", 6),
                    ("quote", 8),
                    ("embed", 9),
                    ("button", 13),
                    ("card", 19),
                    ("cta", 20),
                    ("two_column", 22),
                    ("three_column", 23),
                    ("hero", 26),
                    ("testimonial", 28),
                    ("team_member", 30),
                    ("faq", 32),
                    ("cta_snippet", 34),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: ("apps.blocks.models.RichTextBlock", (), {}),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("author", 5), ("author_title", 5)]],
                        {},
                    ),
                    9: ("apps.blocks.models.EmbedBlock", (), {}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 10), ("link", 11), ("style", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("text", 15),
                                ("image", 16),
                                ("link", 17),
                                ("link_text", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("text", 15),
                                ("button_text", 10),
                                ("button_link", 11),
                                ("button_style", 12),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 2),
                                ("paragraph", 3),
                                ("image", 6),
                                ("quote", 8),
                                ("button", 13),
                            ]
                        ],
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 21), ("right_column", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 21),
                                ("middle_column", 21),
                                ("right_column", 21),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text-white", "White"),
                                ("text-black", "Black"),
                                ("text-gray-800", "Dark Gray"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("subtitle", 24),
                                ("background_image", 16),
                                ("text_color", 25),
                                ("cta_button_text", 18),
                                ("cta_button_link", 17),
                                ("cta_button_style", 12),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.Testimonial,),
                        {},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("testimonial", 27)]], {}),
                    29: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.TeamMember,),
                        {},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("team_member", 29)]], {}),
                    31: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.Faq,),
                        {},
                    ),
                    32: ("wagtail.blocks.StructBlock", [[("faq", 31)]], {}),
                    33: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.Cta,),
                        {},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("cta", 33)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("paragraph", 3),
                    ("image", 6),
                    ("quote", 8),
                    ("embed", 9),
                    ("button", 13),
                    ("card", 19),
                    ("cta", 20),
                    ("two_column", 22),
                    ("three_column", 23),
                    ("hero", 26),
                    ("testimonial", 28),
                    ("team_member", 30),
                    ("faq", 32),
                    ("cta_snippet", 34),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: ("apps.blocks.models.RichTextBlock", (), {}),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("author", 5), ("author_title", 5)]],
                        {},
                    ),
                    9: ("apps.blocks.models.EmbedBlock", (), {}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 10), ("link", 11), ("style", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("text", 15),
                                ("image", 16),
                                ("link", 17),
                                ("link_text", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("text", 15),
                                ("button_text", 10),
                                ("button_link", 11),
                                ("button_style", 12),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 2),
                                ("paragraph", 3),
                                ("image", 6),
                                ("quote", 8),
                                ("button", 13),
                            ]
                        ],
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 21), ("right_column", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 21),
                                ("middle_column", 21),
                                ("right_column", 21),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text-white", "White"),
                                ("text-black", "Black"),
                                ("text-gray-800", "Dark Gray"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("subtitle", 24),
                                ("background_image", 16),
                                ("text_color", 25),
                                ("cta_button_text", 18),
                                ("cta_button_link", 17),
                                ("cta_button_style", 12),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.Testimonial,),
                        {},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("testimonial", 27)]], {}),
                    29: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.TeamMember,),
                        {},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("team_member", 29)]], {}),
                    31: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.Faq,),
                        {},
                    ),
                    32: ("wagtail.blocks.StructBlock", [[("faq", 31)]], {}),
                    33: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (apps.snippets.models.Cta,),
                        {},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("cta", 33)]], {}),
                },
            ),
        ),
    ]
