# Generated by Django 5.2.4 on 2025-08-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True,
                        help_text="The site title used in SEO metadata",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        help_text="The site description used in SEO metadata",
                        null=True,
                    ),
                ),
                (
                    "site_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for the site",
                        null=True,
                    ),
                ),
                (
                    "default_socialsharing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site_favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site favicon used in SEO metadata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site logo used in SEO metadata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
            },
        ),
    ]
