# Generated by Django 5.2.4 on 2025-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(
                blank=True,
                default="Wagtail Starter Kit",
                help_text="The site title",
                max_length=255,
                null=True,
            ),
        ),
    ]
