# Generated by Django 5.2.4 on 2025-08-05 12:48

import django.db.models.deletion
import uuid6
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "to_address",
                    models.CharField(
                        blank=True,
                        help_text="Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.",
                        max_length=255,
                        validators=[wagtail.contrib.forms.models.validate_to_address],
                        verbose_name="to address",
                    ),
                ),
                (
                    "from_address",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="from address"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subject"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "custom_structured_data",
                    models.TextField(
                        blank=True,
                        help_text="Additional structured data for this page in JSON-LD format.",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid6.uuid7, editable=False, unique=True),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="Introduction text for the form"
                    ),
                ),
                (
                    "thank_you_text",
                    models.TextField(
                        blank=True, help_text="Text to display after form submission"
                    ),
                ),
                (
                    "form_fields_streamblock",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 6),
                            ("quote", 8),
                            ("embed", 9),
                            ("button", 13),
                            ("card", 19),
                            ("cta", 20),
                            ("two_column", 22),
                            ("three_column", 23),
                            ("hero", 26),
                            ("text_field", 29),
                            ("email_field", 31),
                            ("textarea_field", 32),
                            ("dropdown_field", 35),
                            ("checkbox_field", 36),
                            ("radio_field", 37),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a header size"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("size", 1)]],
                                {},
                            ),
                            3: ("apps.blocks.models.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("attribution", 5)]],
                                {},
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 7), ("author", 5), ("author_title", 5)]],
                                {},
                            ),
                            9: ("apps.blocks.models.EmbedBlock", (), {}),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": True},
                            ),
                            11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ]
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 10), ("link", 11), ("style", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": True},
                            ),
                            15: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": True},
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            17: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": False},
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("text", 15),
                                        ("image", 16),
                                        ("link", 17),
                                        ("link_text", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("text", 15),
                                        ("button_text", 10),
                                        ("button_link", 11),
                                        ("button_style", 12),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("paragraph", 3),
                                        ("image", 6),
                                        ("quote", 8),
                                        ("button", 13),
                                    ]
                                ],
                                {"required": False},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("left_column", 21), ("right_column", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("left_column", 21),
                                        ("middle_column", 21),
                                        ("right_column", 21),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            25: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("text-white", "White"),
                                        ("text-black", "Black"),
                                        ("text-gray-800", "Dark Gray"),
                                    ]
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("subtitle", 24),
                                        ("background_image", 16),
                                        ("text_color", 25),
                                        ("cta_button_text", 18),
                                        ("cta_button_link", 17),
                                        ("cta_button_style", 12),
                                    ]
                                ],
                                {},
                            ),
                            27: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            28: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "required": False},
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 27), ("required", 28)]],
                                {"icon": "form"},
                            ),
                            30: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "required": False},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 27), ("required", 30)]],
                                {"icon": "mail"},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 27), ("required", 28)]],
                                {"icon": "edit"},
                            ),
                            33: ("wagtail.blocks.CharBlock", (), {}),
                            34: ("wagtail.blocks.ListBlock", (33,), {}),
                            35: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 27), ("options", 34), ("required", 28)]],
                                {"icon": "arrow-down-big"},
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 27), ("required", 28)]],
                                {"icon": "tick"},
                            ),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 27), ("options", 34), ("required", 28)]],
                                {"icon": "radio-full"},
                            ),
                        },
                        help_text="Build your form by adding form fields",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.forms.models.FormMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "clean_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Safe name of the form field, the label converted to ascii_snake_case",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of the form field",
                        max_length=255,
                        verbose_name="label",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("singleline", "Single line text"),
                            ("multiline", "Multi-line text"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("checkbox", "Checkbox"),
                            ("checkboxes", "Checkboxes"),
                            ("dropdown", "Drop down"),
                            ("multiselect", "Multiple select"),
                            ("radio", "Radio buttons"),
                            ("date", "Date"),
                            ("datetime", "Date/time"),
                            ("hidden", "Hidden field"),
                        ],
                        max_length=16,
                        verbose_name="field type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="required"),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                        verbose_name="choices",
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="Default value. Comma or new line separated values supported for checkboxes.",
                        verbose_name="default value",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="help text"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="forms.formpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
