# Generated by Django 5.2.4 on 2025-08-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="form_fields_streamblock",
        ),
    ]
