# Generated by Django 5.2.4 on 2025-08-06 20:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_remove_formpage_form_fields_streamblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="forms.formpage",
            ),
        ),
    ]
