# Generated by Django 5.2.4 on 2025-08-07 21:08

import django.core.serializers.json
import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_remove_formpage_intro_formpage_body_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="submit time"),
                ),
                (
                    "session_key",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Not submitted"),
                            ("complete", "Complete"),
                            ("reviewed", "Under consideration"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="incomplete",
                        max_length=10,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="forms.formpage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "form submission",
                "verbose_name_plural": "form submissions",
                "abstract": False,
                "unique_together": {("page", "session_key"), ("page", "user")},
            },
        ),
    ]
