# Generated by Django 5.2.4 on 2025-08-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forms", "0005_formsubmission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="uuid",
        ),
        migrations.CreateModel(
            name="SubmissionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submission_id", models.TextField()),
                ("data", models.TextField()),
                ("summary", models.TextField()),
                (
                    "submission_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
