# Generated by Django 5.2.4 on 2025-08-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_remove_formpage_uuid_submissionrevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="from_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="to_address",
            field=models.CharField(
                blank=True,
                help_text="Optional - email address to send submissions to",
                max_length=255,
            ),
        ),
    ]
