# Generated by Django 5.2.4 on 2025-08-08 01:24

import apps.snippets.models
import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "custom_structured_data",
                    models.TextField(
                        blank=True,
                        help_text="Additional structured data for this page in JSON-LD format.",
                        null=True,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 6),
                            ("quote", 8),
                            ("embed", 9),
                            ("button", 13),
                            ("card", 19),
                            ("cta", 20),
                            ("testimonial", 22),
                            ("team_member", 24),
                            ("faq", 26),
                            ("cta_snippet", 28),
                            ("two_column", 30),
                            ("three_column", 31),
                            ("hero", 39),
                            ("slider", 40),
                            ("marquee", 41),
                            ("table", 47),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a header size"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("size", 1)]],
                                {},
                            ),
                            3: ("apps.blocks.models.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("attribution", 5)]],
                                {},
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 7), ("author", 5), ("author_title", 5)]],
                                {},
                            ),
                            9: ("apps.blocks.models.EmbedBlock", (), {}),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": True},
                            ),
                            11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ]
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 10), ("link", 11), ("style", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": True},
                            ),
                            15: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": True},
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            17: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": False},
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("text", 15),
                                        ("image", 16),
                                        ("link", 17),
                                        ("link_text", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("text", 15),
                                        ("button_text", 10),
                                        ("button_link", 11),
                                        ("button_style", 12),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (apps.snippets.models.Testimonial,),
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("testimonial", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (apps.snippets.models.TeamMember,),
                                {},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [[("team_member", 23)]],
                                {},
                            ),
                            25: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (apps.snippets.models.Faq,),
                                {},
                            ),
                            26: ("wagtail.blocks.StructBlock", [[("faq", 25)]], {}),
                            27: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (apps.snippets.models.Cta,),
                                {},
                            ),
                            28: ("wagtail.blocks.StructBlock", [[("cta", 27)]], {}),
                            29: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("paragraph", 3),
                                        ("image", 6),
                                        ("quote", 8),
                                        ("embed", 9),
                                        ("button", 13),
                                        ("card", 19),
                                        ("cta", 20),
                                        ("testimonial", 22),
                                        ("team_member", 24),
                                        ("faq", 26),
                                        ("cta_snippet", 28),
                                    ]
                                ],
                                {"required": False},
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [[("left_column", 29), ("right_column", 29)]],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("left_column", 29),
                                        ("middle_column", 29),
                                        ("right_column", 29),
                                    ]
                                ],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            33: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("text-white", "White"),
                                        ("text-black", "Black"),
                                        ("text-gray-800", "Dark Gray"),
                                    ]
                                },
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("subtitle", 32),
                                        ("background_image", 16),
                                        ("text_color", 33),
                                        ("cta_button_text", 18),
                                        ("cta_button_link", 17),
                                        ("cta_button_style", 12),
                                    ]
                                ],
                                {},
                            ),
                            35: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("left", "Left"), ("right", "Right")]},
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("subtitle", 32),
                                        ("image", 4),
                                        ("image_side", 35),
                                        ("cta_button_text", 18),
                                        ("cta_button_link", 17),
                                        ("cta_button_style", 12),
                                    ]
                                ],
                                {},
                            ),
                            37: (
                                "apps.blocks.models.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 14),
                                        ("subtitle", 32),
                                        ("video", 37),
                                        ("text_color", 33),
                                        ("cta_button_text", 18),
                                        ("cta_button_link", 17),
                                        ("cta_button_style", 12),
                                    ]
                                ],
                                {},
                            ),
                            39: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("simple_hero", 34),
                                        ("side_by_side_hero", 36),
                                        ("video_hero", 38),
                                    ]
                                ],
                                {},
                            ),
                            40: ("wagtail.blocks.StructBlock", [[("slides", 29)]], {}),
                            41: ("wagtail.blocks.StructBlock", [[("items", 29)]], {}),
                            42: ("wagtail.blocks.CharBlock", (), {"label": "Column"}),
                            43: (
                                "wagtail.blocks.ListBlock",
                                (42,),
                                {"label": "Header row", "required": False},
                            ),
                            44: ("wagtail.blocks.CharBlock", (), {"label": "Cell"}),
                            45: ("wagtail.blocks.ListBlock", (44,), {}),
                            46: (
                                "wagtail.blocks.ListBlock",
                                (45,),
                                {"label": "Table rows"},
                            ),
                            47: (
                                "wagtail.blocks.StructBlock",
                                [[("table_header", 43), ("table_body", 46)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flex Page",
                "verbose_name_plural": "Flex Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
