# Generated by Django 5.2.4 on 2025-09-11 15:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0002_category_link_portfolioitempage_portfolioitemlink_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.RenameField(
            model_name="portfolioitempage",
            old_name="category",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="projectpage",
            old_name="category",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="resourcepage",
            old_name="category",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="servicepage",
            old_name="category",
            new_name="tag",
        ),
        migrations.RemoveField(
            model_name="showcasepage",
            name="category_filter",
        ),
        migrations.RemoveField(
            model_name="showcasepage",
            name="entity_types_to_display",
        ),
        migrations.AddField(
            model_name="showcasepage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Optional introduction text for the showcase page"
            ),
        ),
        migrations.CreateModel(
            name="ShowcaseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Heading for this section", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for this section"
                    ),
                ),
                (
                    "showcase_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="pages.showcasepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShowcaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pages.showcasesection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
