# Generated by Django 5.2.4 on 2025-09-15 14:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_rename_category_tag_alter_tag_options_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showcaseitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="showcaseitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="showcaseitem",
            name="object_id",
        ),
        migrations.AddField(
            model_name="showcaseitem",
            name="description",
            field=models.TextField(blank=True, help_text="Description for this item"),
        ),
        migrations.AddField(
            model_name="showcaseitem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional page to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="showcaseitem",
            name="title",
            field=models.CharField(
                default="Untitled", help_text="Title for this item", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="ShowcaseItemLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "target",
                    models.CharField(
                        choices=[("_self", "Same Window"), ("_blank", "New Window")],
                        default="_self",
                        max_length=10,
                    ),
                ),
                (
                    "item",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="pages.showcaseitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
