# Generated by Django 5.2.4 on 2025-09-15 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_resourceshowcaseitem_remove_servicelink_link_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourcePage",
        ),
    ]
